version: '3.9'

services:
  api:
    command: >
      sh -c "npm run start:prod"
    container_name: cont_api_app_dev
    depends_on:    
      - postgres
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - 3000:3000
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=app_dev_user
      - DB_PASSWORD=app_dev_password
      - DB_NAME=app_dev
      - POKEMON_API_URL=https://pokeapi.co/api/v2
    restart: unless-stopped

  postgres:
    image: postgres:16
    container_name: cont_postgres_app_dev    
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: app_dev_user
      POSTGRES_PASSWORD: app_dev_password
      POSTGRES_DB: app_dev
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_dev_data:
