version: 2.1
orbs:
  node: circleci/node@5.0.2
  coveralls: coveralls/coveralls@2.2.5

jobs:
  build_and_test: # this can be any name you choose
    docker:
      # Primary container
      - image: cimg/node:20.9.0
        environment:
          DATABASE_HOST: 0.0.0.0
          DATABASE_PORT: 5432
          DATABSE_USER: app_test_user
          DATABASE_PASSWORD: app_test_password
          DATABASE_NAME: app_test_DB
          POKEMON_API_URL: https://pokeapi.co/api/v2
          COVERALLS_REPO_TOKEN: rIvL7qyGs9unSwD2Mp3dBzPKjwsLzBoAc
      # Service container image
      - image: cimg/postgres:16.0
        environment:
          POSTGRES_USER: app_test_user
          POSTGRES_PASSWORD: app_test_password
          POSTGRES_DB: app_test_DB
    executor: node/default # use the default executor defined within the orb
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: COVERALLS_REPO_TOKEN=rIvL7qyGs9unSwD2Mp3dBzPKjwsLzBoAc npm run test:cov
          name: Run tests     
      - run:
          command: npm run build
          name: Install and make
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
      - coveralls/upload:
          parallel: true
          flag_name: Test 1
          verbose: true      
workflows:
  build_test_deploy: # this can be any name you choose
    jobs:
      - build_and_test
