version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  build_and_test:
    docker:
      - image: cimg/node:20.9.0
        environment:
          DATABASE_HOST: localhost
          DATABASE_PORT: 5432
          DATABASE_USER: app_test_user
          DATABASE_PASSWORD: app_test_password
          DATABASE_NAME: app_test_DB
          POKEMON_API_URL: https://pokeapi.co/api/v2

      - image: cimg/postgres:16.0
        environment:
          POSTGRES_USER: app_test_user
          POSTGRES_PASSWORD: app_test_password
          POSTGRES_DB: app_test_DB

    steps:
      - checkout

      - node/install-packages:
          pkg-manager: npm

      - run:
          name: Run e2e tests with coverage
          command: npm run test:cov

      - run:
          name: Build app
          command: npm run build

      - run:
          name: Upload coverage to Coveralls
          command: npx coveralls --service=circleci < coverage/lcov.info

workflows:
  build_test_deploy:
    jobs:
      - build_and_test
